### ISSUE TITLE
intl_translation:generate_from_arb : "Parsing errors in ..."

### ISSUE THREAD

**Issue by jimmyff** [dart-lang/intl_translation#154]
Since upgrading to support null saftey I can no longer run `intl_translation:generate_from_arb` as I get the following error:

```
> Executing task in folder esc_core: dart run intl_translation:generate_from_arb --output-dir=lib/src/l10n/messages --no-use-deferred-loading lib/src/l10n/messages.dart lib/src/l10n/arb/intl_*.arb <

Building package executable... (3.6s)
Built intl_translation:generate_from_arb.
Error in parsing lib/src/l10n/messages.dart, no messages extracted.
Unhandled exception:
Invalid argument(s): Parsing errors in lib/src/l10n/messages.dart
#0      MessageExtraction._parseCompilationUnit (package:intl_translation/extract_messages.dart:117:7)
#1      MessageExtraction.parseContent (package:intl_translation/extract_messages.dart:102:14)
#2      MessageExtraction.parseFile (package:intl_translation/extract_messages.dart:87:12)
#3      main.<anonymous closure> (file:///home/jimmyff/.pub-cache/hosted/pub.dartlang.org/intl_translation-0.17.10+1/bin/generate_from_arb.dart:113:33)
#4      MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
#5      ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
#6      main (file:///home/jimmyff/.pub-cache/hosted/pub.dartlang.org/intl_translation-0.17.10+1/bin/generate_from_arb.dart:116:23)
#7      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
The terminal process "bash '-c', 'dart run intl_translation:generate_from_arb --output-dir=lib/src/l10n/messages --no-use-deferred-loading lib/src/l10n/messages.dart lib/src/l10n/arb/intl_*.arb'" terminated with exit code: 255.

Terminal will be reused by tasks, press any key to close it.

```

Any advice on how to fix?

**Comment by mosuem** [comment]
This should be fixed by now, or be fixed with #165 .
