### ISSUE TITLE
Error in <unknown source>: Expected to find ','.

### ISSUE THREAD

**Issue by jaumard** [dart-lang/intl_translation#53]
I have done a package upgrade and now I'm getting this crash: 

```
Extracting messages from lib/l10n/common_localizations.dart to lib/l10n/messages/common_en.json...
Error in parsing lib/l10n/common_localizations.dart, no messages extracted.
Unhandled exception:
Error in <unknown source>: Expected to find ','.

#0      _parseSource (package:analyzer/analyzer.dart:114:52)
#1      parseCompilationUnit (package:analyzer/analyzer.dart:42:10)
#2      MessageExtraction._parseCompilationUnit (package:intl_translation/extract_messages.dart:94:16)
#3      MessageExtraction.parseFile (package:intl_translation/extract_messages.dart:81:14)
#4      main (file:///Users/jaumard/StudioProjects/kiwi_mobile2/bin/extract_messages.dart:28:16)
#5      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#6      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
pub finished with exit code 255

```

My code is: 
```
final extraction = MessageExtraction();
final inputFile = '$inputDir/$component$inputFileSuffix';
print('Extracting messages from $inputFile to $outputDir/$component$outputFileSuffix...');

final allMessages = [];
extraction.parseFile(File(inputFile)).forEach((k, v) => allMessages.add(toJSON(v)));
```

Previously it was working fine, to make it work again I had to use: 
```
dependency_overrides:
  analyzer: 0.33.3
```
All version after that make my code crash (0.33.4 and 0.33.5 are not compatible with my SDK dart, 0.33.6 and more give me the crash)

**Comment by alan-knight** [comment]
Sorry for the delay looking at this. That seems odd, as we're using newer versions in a lot of places. Can you find what the message is that's causing the problem.  The error looks like the analyzer is having trouble with your source, maybe there's something odd in there that became invalid in the most recent versions?

I think it should be throwing an AnalyzerErrorGroup on your parsing, so you should be able to catch that and find more information.
