### ISSUE TITLE
Cannot find parameter named A in message named B

### ISSUE THREAD

**Issue by vintage** [dart-lang/intl_translation#80]
It seems there is an issue with lexical part of the ICU parser which cannot handle properly variations of `Intl.message` and `Intl.gender` properly.

```
// localizations.dart
class MyLocalizations {
  String test(String gender) => Intl.message(
    "Hi ${Intl.gender(gender, female: 'women', other: 'men')}",
    name: "test",
    args: [gender],
  );
}
````

Running the command to extract data from above file into arb:

```
flutter pub run intl_translation:extract_to_arb \
	--locale pl \
	--output-dir=lib/l10n/autogenerated \
	--warnings-are-errors \
	localizations.dart
```

New files has been generated under `/lib/l10n/autogenerated/intl_messages.arb`:

```
{
  "@@locale": "pl",
  "@@last_modified": "2019-11-28T16:25:05.527968",
  "test": "Hi {gender,select, female{women}other{men}}",
  "@test": {
    "type": "text",
    "placeholders": {
      "gender": {}
    }
  }
}
```

So far, so good, but when performing the last step the intl crashes:

```
flutter pub run intl_translation:generate_from_arb \
	--output-dir=lib/l10n/autogenerated \
	--no-use-deferred-loading \
	localizations.dart \
	lib/l10n/autogenerated/intl_*.arb
```

```
Unhandled exception:
Invalid argument(s): Cannot find parameter named 'WOMEN' in message named 'test'. Available parameters are [gender]
#0      VariableSubstitution.index (package:intl_translation/src/intl_message.dart:396:7)
#1      VariableSubstitution.variableName (package:intl_translation/src/intl_message.dart:411:57)
#2      VariableSubstitution.toCode (package:intl_translation/src/intl_message.dart:416:21)
#3      CompositeMessage.toCode.<anonymous closure> (package:intl_translation/src/intl_message.dart:352:41)
#4      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:29)
#5      ListIterable.join (dart:_internal/iterable.dart:165:22)
#6      CompositeMessage.toCode (package:intl_translation/src/intl_message.dart:352:51)
#7      MainMessage.addTranslation (package:intl_translation/src/intl_message.dart:520:39)
#8      MessageGeneration.generateIndividualMessageFile (package:intl_translation/generate_localized.dart:87:18)
#9      generateLocaleFile (file:///usr/local/opt/flutter/.pub-cache/hosted/pub.dartlang.org/intl_translation-0.17.7/bin/generate_from_arb.dart:162:14)
#10     main.<anonymous closure> (file:///usr/local/opt/flutter/.pub-cache/hosted/pub.dartlang.org/intl_translation-0.17.7/bin/generate_from_arb.dart:115:5)
#11     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#12     main (file:///usr/local/opt/flutter/.pub-cache/hosted/pub.dartlang.org/intl_translation-0.17.7/bin/generate_from_arb.dart:114:20)
#13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

It works well when changing the sentence `"Hi ${Intl.gender(gender, female: 'women', other: 'men')}"` to one of the followings:

1. "${Intl.gender(gender, female: 'women', other: 'men')} Hi"
2. "Hi ${Intl.gender(gender, female: 'ą', other: 'ć')}"

The only feasible solution for now which works is to omit the `Intl.message` part and use only the `Intl.gender` - but it introduces repeated amount of text. Like so:

```
// fixed_localizations.dart
class MyLocalizations {
  String test(String gender) => Intl.gender(
    gender,
    female: "Hi women",
    other: "Hi man",
    name: "test",
    args: [gender],
  );
}
````

**Comment by alan-knight** [comment]
Well that's peculiar, and definitely seems like a bug. However, I note that it's generally recommended practice with translations to include the context of the full message, even if it introduces redundancy. In some languages, the translation of just 'women' standalone, might be different than 'Hi women.'  e.g. in French Google translates women as "femmes" , "hi" as "salut", and "hi women" as "salut les femmes".

**Comment by mosuem** [comment]
Closing in favor of #86 for the issue of nesting calls in general.
